// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: test3

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_RootPanel;
lv_obj_t * ui_PanelPH;
lv_obj_t * ui_LabelPH;
lv_obj_t * ui_PanelCONDUCT;
lv_obj_t * ui_LabelCONDUCT;
lv_obj_t * ui_PanelTDS;
lv_obj_t * ui_LabelTDS;
lv_obj_t * ui_DoDucValue;
lv_obj_t * ui_Phvalue;
lv_obj_t * ui_TDSvalue;
lv_obj_t * ui_LbPH;
lv_obj_t * ui_LabelDoDuc;
lv_obj_t * ui_Labelppm;
lv_obj_t * ui_watertankpn1;
lv_obj_t * ui_Image10;
lv_obj_t * ui_percentwatermask;
lv_obj_t * ui_percentwater;
lv_obj_t * ui_LabelPercent;
lv_obj_t * ui_Thermos;
lv_obj_t * ui_Image9;
lv_obj_t * ui_TemperatureMask;
lv_obj_t * ui_Temperature;
lv_obj_t * ui_Unit_Temper;
lv_obj_t * ui_Timepn;
lv_obj_t * ui_HourMask;
lv_obj_t * ui_MinuteMask;
lv_obj_t * ui_SecondMask;
lv_obj_t * ui_doit1;
lv_obj_t * ui_doit2;
lv_obj_t * ui_Hour;
lv_obj_t * ui_Minute;
lv_obj_t * ui_Second;
lv_obj_t * ui_Day;
lv_obj_t * ui_month;
lv_obj_t * ui_year;
lv_obj_t * ui_WeekDay;
lv_obj_t * WifiStatus;
lv_obj_t * ui_Image4;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
