// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: test3

#ifndef _TEST3_UI_H
#define _TEST3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_RootPanel;
extern lv_obj_t * ui_PanelPH;
extern lv_obj_t * ui_LabelPH;
extern lv_obj_t * ui_PanelCONDUCT;
extern lv_obj_t * ui_LabelCONDUCT;
extern lv_obj_t * ui_PanelTDS;
extern lv_obj_t * ui_LabelTDS;
extern lv_obj_t * ui_DoDucValue;
extern lv_obj_t * ui_Phvalue;
extern lv_obj_t * ui_TDSvalue;
extern lv_obj_t * ui_LbPH;
extern lv_obj_t * ui_LabelDoDuc;
extern lv_obj_t * ui_Labelppm;
extern lv_obj_t * ui_watertankpn1;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_percentwatermask;
extern lv_obj_t * ui_percentwater;
extern lv_obj_t * ui_LabelPercent;
extern lv_obj_t * ui_Thermos;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_TemperatureMask;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Unit_Temper;
extern lv_obj_t * ui_Timepn;
extern lv_obj_t * ui_HourMask;
extern lv_obj_t * ui_MinuteMask;
extern lv_obj_t * ui_SecondMask;
extern lv_obj_t * ui_doit1;
extern lv_obj_t * ui_doit2;
extern lv_obj_t * ui_Hour;
extern lv_obj_t * ui_Minute;
extern lv_obj_t * ui_Second;
extern lv_obj_t * ui_Day;
extern lv_obj_t * ui_month;
extern lv_obj_t * ui_year;
extern lv_obj_t * ui_WeekDay;
extern lv_obj_t * WifiStatus;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1310565656);    // assets/oil-storage-tank (1).png
LV_IMG_DECLARE(
    ui_img_472504809);    // assets/thermometer-temperature-white-icon-transparent-png-701751694972457fkxevmgt6i__1___2_-removebg-preview.png
LV_IMG_DECLARE(ui_img_1365894730);    // assets/images__1_-removebg-preview (1).png
LV_IMG_DECLARE(ui_img_2139209214);    // assets/f156d1a4da92b95bf3b4c2a6739f688f-removebg-preview (1).png



LV_FONT_DECLARE(ui_font_FontNew);
LV_FONT_DECLARE(ui_font_FontNew24);
LV_FONT_DECLARE(ui_font_FontNew40);
LV_FONT_DECLARE(ui_font_Font1);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
