// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: test3

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RootPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RootPanel, lv_pct(102));
    lv_obj_set_height(ui_RootPanel, lv_pct(100));
    lv_obj_set_x(ui_RootPanel, 1);
    lv_obj_set_y(ui_RootPanel, 0);
    lv_obj_set_align(ui_RootPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RootPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RootPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RootPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RootPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RootPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RootPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPH = lv_obj_create(ui_RootPanel);
    lv_obj_set_width(ui_PanelPH, lv_pct(65));
    lv_obj_set_height(ui_PanelPH, lv_pct(10));
    lv_obj_set_x(ui_PanelPH, -35);
    lv_obj_set_y(ui_PanelPH, 100);
    lv_obj_set_align(ui_PanelPH, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPH, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPH, lv_color_hex(0xB707FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PanelPH, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPH, lv_color_hex(0xB707FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PanelPH, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelPH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelPH, &ui_font_FontNew, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPH = lv_label_create(ui_PanelPH);
    lv_obj_set_width(ui_LabelPH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPH, "PH SENSOR");
    lv_obj_set_style_text_color(ui_LabelPH, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCONDUCT = lv_obj_create(ui_RootPanel);
    lv_obj_set_width(ui_PanelCONDUCT, lv_pct(65));
    lv_obj_set_height(ui_PanelCONDUCT, lv_pct(10));
    lv_obj_set_x(ui_PanelCONDUCT, -35);
    lv_obj_set_y(ui_PanelCONDUCT, 140);
    lv_obj_set_align(ui_PanelCONDUCT, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCONDUCT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCONDUCT, lv_color_hex(0xE8610B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCONDUCT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCONDUCT, lv_color_hex(0xE8610B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCONDUCT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCONDUCT = lv_label_create(ui_PanelCONDUCT);
    lv_obj_set_width(ui_LabelCONDUCT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCONDUCT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCONDUCT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCONDUCT, "Conductivity");
    lv_obj_set_style_text_color(ui_LabelCONDUCT, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCONDUCT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCONDUCT, &ui_font_FontNew, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTDS = lv_obj_create(ui_RootPanel);
    lv_obj_set_width(ui_PanelTDS, lv_pct(65));
    lv_obj_set_height(ui_PanelTDS, lv_pct(12));
    lv_obj_set_x(ui_PanelTDS, -35);
    lv_obj_set_y(ui_PanelTDS, 60);
    lv_obj_set_align(ui_PanelTDS, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTDS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTDS, lv_color_hex(0x0ADECB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTDS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTDS, lv_color_hex(0x0ADECB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTDS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTDS = lv_label_create(ui_PanelTDS);
    lv_obj_set_width(ui_LabelTDS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTDS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTDS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTDS, "TDS SENSOR");
    lv_obj_set_style_text_color(ui_LabelTDS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTDS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTDS, &ui_font_FontNew, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoDucValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_DoDucValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoDucValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DoDucValue, 35);
    lv_obj_set_y(ui_DoDucValue, 140);
    lv_obj_set_align(ui_DoDucValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DoDucValue, "0000");
    lv_obj_set_style_text_color(ui_DoDucValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DoDucValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DoDucValue, &ui_font_FontNew, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Phvalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Phvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Phvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Phvalue, 35);
    lv_obj_set_y(ui_Phvalue, 100);
    lv_obj_set_align(ui_Phvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Phvalue, "00.00");
    lv_obj_set_style_text_color(ui_Phvalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Phvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Phvalue, &ui_font_FontNew, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TDSvalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TDSvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TDSvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TDSvalue, 35);
    lv_obj_set_y(ui_TDSvalue, 60);
    lv_obj_set_align(ui_TDSvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TDSvalue, "0000");
    lv_obj_set_style_text_color(ui_TDSvalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TDSvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TDSvalue, &ui_font_FontNew, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbPH = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LbPH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbPH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbPH, 65);
    lv_obj_set_y(ui_LbPH, 100);
    lv_obj_set_align(ui_LbPH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbPH, "ph");
    lv_obj_set_style_text_color(ui_LbPH, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbPH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbPH, &ui_font_FontNew, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDoDuc = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelDoDuc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDoDuc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDoDuc, 65);
    lv_obj_set_y(ui_LabelDoDuc, 140);
    lv_obj_set_align(ui_LabelDoDuc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDoDuc, "NTU");
    lv_obj_set_style_text_color(ui_LabelDoDuc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDoDuc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDoDuc, &ui_font_FontNew, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelppm = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Labelppm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelppm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelppm, 65);
    lv_obj_set_y(ui_Labelppm, 60);
    lv_obj_set_align(ui_Labelppm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelppm, "ppm");
    lv_obj_set_style_text_color(ui_Labelppm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelppm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelppm, &ui_font_FontNew, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watertankpn1 = lv_obj_create(ui_Screen1);
    lv_obj_set_height(ui_watertankpn1, 55);
    lv_obj_set_width(ui_watertankpn1, lv_pct(100));
    lv_obj_set_x(ui_watertankpn1, 0);
    lv_obj_set_y(ui_watertankpn1, -70);
    lv_obj_set_align(ui_watertankpn1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_watertankpn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_watertankpn1, lv_color_hex(0xCF0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watertankpn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_watertankpn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_watertankpn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_watertankpn1);
    lv_img_set_src(ui_Image10, &ui_img_1310565656);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image10, -50);
    lv_obj_set_y(ui_Image10, 0);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_percentwatermask = lv_label_create(ui_watertankpn1);
    lv_obj_set_width(ui_percentwatermask, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_percentwatermask, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_percentwatermask, 18);
    lv_obj_set_y(ui_percentwatermask, 3);
    lv_obj_set_align(ui_percentwatermask, LV_ALIGN_CENTER);
    lv_label_set_text(ui_percentwatermask, "00.0");
    lv_obj_set_style_text_color(ui_percentwatermask, lv_color_hex(0x5B5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_percentwatermask, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_percentwatermask, &ui_font_FontNew40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percentwater = lv_label_create(ui_watertankpn1);
    lv_obj_set_width(ui_percentwater, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_percentwater, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_percentwater, 15);
    lv_obj_set_y(ui_percentwater, 0);
    lv_obj_set_align(ui_percentwater, LV_ALIGN_CENTER);
    lv_label_set_text(ui_percentwater, "00.0");
    lv_obj_set_style_text_color(ui_percentwater, lv_color_hex(0x02A1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_percentwater, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_percentwater, &ui_font_FontNew40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPercent = lv_label_create(ui_watertankpn1);
    lv_obj_set_width(ui_LabelPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPercent, 70);
    lv_obj_set_y(ui_LabelPercent, 0);
    lv_obj_set_align(ui_LabelPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPercent, "%");
    lv_obj_set_style_text_color(ui_LabelPercent, lv_color_hex(0x02A1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPercent, &ui_font_FontNew40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thermos = lv_obj_create(ui_Screen1);
    lv_obj_set_height(ui_Thermos, 70);
    lv_obj_set_width(ui_Thermos, lv_pct(100));
    lv_obj_set_x(ui_Thermos, 0);
    lv_obj_set_y(ui_Thermos, -6);
    lv_obj_set_align(ui_Thermos, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Thermos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Thermos, lv_color_hex(0x00C0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Thermos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Thermos, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Thermos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_Thermos);
    lv_img_set_src(ui_Image9, &ui_img_472504809);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, -50);
    lv_obj_set_y(ui_Image9, 0);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TemperatureMask = lv_label_create(ui_Thermos);
    lv_obj_set_width(ui_TemperatureMask, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureMask, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureMask, 18);
    lv_obj_set_y(ui_TemperatureMask, 3);
    lv_obj_set_align(ui_TemperatureMask, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureMask, "00.0");
    lv_obj_set_style_text_color(ui_TemperatureMask, lv_color_hex(0x5B5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemperatureMask, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperatureMask, &ui_font_FontNew40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature = lv_label_create(ui_Thermos);
    lv_obj_set_width(ui_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature, 15);
    lv_obj_set_y(ui_Temperature, 0);
    lv_obj_set_align(ui_Temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature, "00.0");
    lv_obj_set_style_text_color(ui_Temperature, lv_color_hex(0xFC0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperature, &ui_font_FontNew40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Unit_Temper = lv_label_create(ui_Thermos);
    lv_obj_set_width(ui_Unit_Temper, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Unit_Temper, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Unit_Temper, 70);
    lv_obj_set_y(ui_Unit_Temper, 0);
    lv_obj_set_align(ui_Unit_Temper, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Unit_Temper, "*C");
    lv_obj_set_style_text_color(ui_Unit_Temper, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Unit_Temper, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Unit_Temper, &ui_font_FontNew40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Timepn = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Timepn, lv_pct(100));
    lv_obj_set_height(ui_Timepn, lv_pct(23));
    lv_obj_set_x(ui_Timepn, 0);
    lv_obj_set_y(ui_Timepn, -136);
    lv_obj_set_align(ui_Timepn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Timepn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Timepn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Timepn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Timepn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Timepn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Timepn, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Timepn, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_HourMask = lv_label_create(ui_Timepn);
    lv_obj_set_width(ui_HourMask, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HourMask, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HourMask, -57);
    lv_obj_set_y(ui_HourMask, -2);
    lv_obj_set_align(ui_HourMask, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HourMask, "00");
    lv_obj_set_style_text_color(ui_HourMask, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HourMask, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HourMask, &ui_font_FontNew40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinuteMask = lv_label_create(ui_Timepn);
    lv_obj_set_width(ui_MinuteMask, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinuteMask, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinuteMask, 3);
    lv_obj_set_y(ui_MinuteMask, -2);
    lv_obj_set_align(ui_MinuteMask, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinuteMask, "00");
    lv_obj_set_style_text_color(ui_MinuteMask, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinuteMask, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinuteMask, &ui_font_FontNew40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SecondMask = lv_label_create(ui_Timepn);
    lv_obj_set_width(ui_SecondMask, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SecondMask, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SecondMask, 63);
    lv_obj_set_y(ui_SecondMask, -2);
    lv_obj_set_align(ui_SecondMask, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SecondMask, "00");
    lv_obj_set_style_text_color(ui_SecondMask, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SecondMask, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SecondMask, &ui_font_FontNew40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_doit1 = lv_label_create(ui_Timepn);
    lv_obj_set_width(ui_doit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_doit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_doit1, -30);
    lv_obj_set_y(ui_doit1, -5);
    lv_obj_set_align(ui_doit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_doit1, ":");
    lv_obj_set_style_text_color(ui_doit1, lv_color_hex(0x04FC1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_doit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_doit1, &ui_font_FontNew40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_doit2 = lv_label_create(ui_Timepn);
    lv_obj_set_width(ui_doit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_doit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_doit2, 30);
    lv_obj_set_y(ui_doit2, -5);
    lv_obj_set_align(ui_doit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_doit2, ":");
    lv_obj_set_style_text_color(ui_doit2, lv_color_hex(0x04FC1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_doit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_doit2, &ui_font_FontNew40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hour = lv_label_create(ui_Timepn);
    lv_obj_set_width(ui_Hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Hour, -60);
    lv_obj_set_y(ui_Hour, -5);
    lv_obj_set_align(ui_Hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Hour, "00");
    lv_obj_set_style_text_color(ui_Hour, lv_color_hex(0x04FC1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Hour, &ui_font_FontNew40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Minute = lv_label_create(ui_Timepn);
    lv_obj_set_width(ui_Minute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Minute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Minute, 0);
    lv_obj_set_y(ui_Minute, -5);
    lv_obj_set_align(ui_Minute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Minute, "00");
    lv_obj_set_style_text_color(ui_Minute, lv_color_hex(0x04FC1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Minute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Minute, &ui_font_FontNew40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Second = lv_label_create(ui_Timepn);
    lv_obj_set_width(ui_Second, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Second, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Second, 60);
    lv_obj_set_y(ui_Second, -5);
    lv_obj_set_align(ui_Second, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Second, "00");
    lv_obj_set_style_text_color(ui_Second, lv_color_hex(0x04FC1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Second, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Second, &ui_font_FontNew40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Day = lv_label_create(ui_Timepn);
    lv_obj_set_width(ui_Day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Day, 0);
    lv_obj_set_y(ui_Day, 25);
    lv_obj_set_align(ui_Day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Day, "05");
    lv_obj_set_style_text_color(ui_Day, lv_color_hex(0xE3F909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Day, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Day, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_month = lv_label_create(ui_Timepn);
    lv_obj_set_width(ui_month, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_month, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_month, 20);
    lv_obj_set_y(ui_month, 25);
    lv_obj_set_align(ui_month, LV_ALIGN_CENTER);
    lv_label_set_text(ui_month, "03");
    lv_obj_set_style_text_color(ui_month, lv_color_hex(0xE3F909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_month, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_month, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_year = lv_label_create(ui_Timepn);
    lv_obj_set_width(ui_year, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_year, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_year, 40);
    lv_obj_set_y(ui_year, 25);
    lv_obj_set_align(ui_year, LV_ALIGN_CENTER);
    lv_label_set_text(ui_year, "2025");
    lv_obj_set_style_text_color(ui_year, lv_color_hex(0xE3F909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_year, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_year, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeekDay = lv_label_create(ui_Timepn);
    lv_obj_set_width(ui_WeekDay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeekDay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeekDay, -40);
    lv_obj_set_y(ui_WeekDay, 25);
    lv_obj_set_align(ui_WeekDay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeekDay, "Wednesday,");
    lv_obj_set_style_text_color(ui_WeekDay, lv_color_hex(0xE3F909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeekDay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeekDay, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    WifiStatus = lv_img_create(ui_Timepn);
    lv_img_set_src(WifiStatus, &ui_img_1365894730);
    lv_obj_set_width(WifiStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(WifiStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(WifiStatus, 68);
    lv_obj_set_y(WifiStatus, 27);
    lv_obj_set_align(WifiStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(WifiStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(WifiStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Timepn);
    lv_img_set_src(ui_Image4, &ui_img_2139209214);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 109);
    lv_obj_set_y(ui_Image4, 12);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
